Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Cadastro()
        {
            TipoPerfil tipoPerfil = LoginValidacao.ValidaPerfil();
            if (tipoPerfil == TipoPerfil.Administrador)
                return View("\\Views\\Home\\Cadastro.cshtml");
            else if (tipoPerfil == TipoPerfil.Usuario)
                return View("\\Views\\Home\\ErroAutorizacao.cshtml");
            else
            {   
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }

        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/CadastroUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;

namespace Projeto_Estoque.Controllers
{
    public class CadastroUsuarioController : Controller
    {
      
        public IActionResult Cadastro(Usuario novoUsuario)
        {
            return View("\\Views\\Home\\CadastroUsuario.cshtml");
        }

    
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class ConsultaController : Controller
    {
        //public IActionResult ConsultaProduto()
        //{
        //    return View("\\Views\\Home\\Consulta.cshtml");
        //}

        public IActionResult ConsultaProduto(Produto produto)
        {
            if(produto.Nome != null)
                ViewData["Message"] = produto.Nome;
            else
                ViewData["Message"] = "Não funcionou";

            TipoPerfil tipoPerfil = LoginValidacao.ValidaPerfil();

            if (tipoPerfil == TipoPerfil.Usuario || tipoPerfil == TipoPerfil.Administrador)
            {
                return View("\\Views\\Home\\Consulta.cshtml", produto);               
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
                
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            TipoPerfil tipoPerfil = LoginValidacao.ValidaPerfil();

            if (tipoPerfil == TipoPerfil.Usuario || tipoPerfil == TipoPerfil.Administrador)
            {
                return View();
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
           
        }

       

      

     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login(Usuario usuario)
        {     
                return View("\\Views\\Home\\Login.cshtml");
        }

        public IActionResult Logar(Usuario usuario)
        {

            if (!LoginValidacao.ValidaLogin(usuario))
            {
                ModelState.AddModelError("Email", "Email ou senha estão incorretos");
                ModelState.AddModelError("Senha", "Email ou senha estão incorretos");
            }
            LoginValidacao.CarregaTipoPerfil(usuario);
            if (ModelState.IsValid)
            {
                return View("\\Views\\Home\\Index.cshtml");
            }
            else
            {

                return View("\\Views\\Home\\Login.cshtml");
            }
        }
        public IActionResult Sair()
        {
            LoginValidacao.SairSistema();
            return Login(Usuario.GetInstance());
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class RelatorioController : Controller
    {
        public IActionResult Relatorio()
        {
            TipoPerfil tipoPerfil = LoginValidacao.ValidaPerfil();

            if (tipoPerfil == TipoPerfil.Usuario || tipoPerfil == TipoPerfil.Administrador)
            {
                return View("\\Views\\Home\\Relatorio.cshtml");
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
            
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/About - Cópia.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Cadastro.cshtml
@model Produto
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Cadastro de Produtos";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

@using (Html.BeginForm("CadastrarProduto", "Cadastro", FormMethod.Post))
{
    <div style="display:grid; width:50%">
        @Html.Label("Produto")
        @Html.TextBoxFor(a => a.Nome)
        @Html.ValidationMessageFor(x => x.Nome)

        @Html.Label("Categoria")
        @Html.TextBoxFor(a => a.Categoria)
        @Html.ValidationMessageFor(x => x.Categoria)

        @Html.Label("Preço")
        @Html.TextBoxFor(a => a.Valor, new {@class = "money"})
        @Html.ValidationMessageFor(x => x.Valor)

        @Html.Label("Descrição")
        @Html.TextAreaFor(a => a.Descricao, new { style = "Resize:none; overflow: hidden;height: 160%" })
        @Html.ValidationMessageFor(x => x.Descricao)

        <button type="submit" style="margin-top: 10%; width:25%">Salvar  </button>


        @* <button type="submit" style="margin-top: 10%; width:25%">Cancelar  </button>*@
    </div>
}
<form action="/Home/Index" method="get">
    <input type="submit" value="Cancelar" id="frm1_submit" style="width:12.5%" />
</form>

Views/Home/CadastroUsuario.cshtml
@{
    ViewData["Title"] = "Cadastro Usuário";
}
<h2>@ViewData["Title"]</h2>

Views/Home/Consulta.cshtml
@model Produto
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Consulta Produto";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

Views/Home/ErroAutorizacao.cshtml
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Não Autorizado";
}
<div style="margin:15%">
    <b> Você não tem autorização para acessar essa página. Contacte o administrador do Sistema.</b>
    <a asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
</div>

Views/Home/Index.cshtml
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Projeto Estoque";
}
   
    <div>       
        <div class="divTable">
            <h3>Resumo Estoque</h3>
            <table id="tg-xQLBb" class="tg">
                <thead>
                    <tr>
                        <th class="tg-ul38">Código</th>
                        <th class="tg-ul38">Produto</th>
                        <th class="tg-ul38">Categoria</th>
                        <th class="tg-ul38">Valor</th>
                        <th class="tg-ul38">Estoque</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="tg-0lax">1</td>
                        <td class="tg-0lax">2</td>
                        <td class="tg-0lax">3</td>
                        <td class="tg-0lax">4</td>
                        <td class="tg-0lax">5</td>
                    </tr>
                    <tr>
                        <td class="tg-0lax">5</td>
                        <td class="tg-0lax">4</td>
                        <td class="tg-0lax">3</td>
                        <td class="tg-0lax">2</td>
                        <td class="tg-0lax">1</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

Views/Home/Login.cshtml
@model Usuario
@{
    ViewData["Title"] = "Login Usuário";
}
<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm("Logar", "Login", FormMethod.Post))
{
<div>
    @Html.Label("Email")
    @Html.TextBoxFor(a => a.email)
    @Html.ValidationMessageFor(x => x.email)
    @Html.Label("Senha")
    @Html.TextBoxFor(a => a.Senha)
    @Html.ValidationMessageFor(x => x.Senha)
    <button type="submit"><i class="glyphicon glyphicon-user"></i></button>
</div>
    

}

Views/Home/Relatorio.cshtml
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Relatório por Produto";
}
<h2>@ViewData["Title"]</h2>

Views/Home/UsuarioCadastro.cshtml
@{
    ViewData["Title"] = "Cadastro Realizado com sucesso";
}
<h2>@ViewData["Title"]</h2>

<li><a asp-area="" asp-controller="Login" asp-action="Login">Relatório</a></li>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


     
 
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

            </div>

            <div class="navbar-collapse collapse">


                </div>

            </div>

    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    </body>
</html>

Views/Shared/_LayoutLogado.cshtml
@model  Produto
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

        
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Projeto Estoque</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastro</a></li>
                    <li><a asp-area="" asp-controller="Relatorio" asp-action="Relatorio">Relatório</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Sair">Sair</a></li>

                </ul>
                <span class="fa fa-search form-control-feedback"></span>
                <div class="form-group" style="float:right;align-items: center;padding: 10px;">
                    @using (Html.BeginForm("ConsultaProduto", "Consulta", FormMethod.Get))
                    {

                        @Html.TextBoxFor(a => a.Nome)
                        <button  type="submit"><i class="glyphicon glyphicon-search"></i></button>

                    }

                </div>

            </div>
          
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr style="margin-top: 10%;"/>
        <footer>
            <p>&copy; 2020 - Projeto_Estoque</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jQueryMask/jquery.mask.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>